### ISSUE TITLE
GraphicsMagick support

### ISSUE THREAD

**Issue by lu-x** [elixir-waffle/waffle#113]
### Environment

* Elixir version (elixir -v): 1.14.3
* Waffle version (mix deps): 1.1.7
* Operating system: OSX 13.2.1

### Expected behavior
Waffle supports the use of GraphicsMagick as it's told to be a very good alternative (see http://www.graphicsmagick.org/).

### Actual behavior
It's not possible to use GraphicsMagick because the command structure is different than for ImageMagick. Would be super cool to be able to do the switch. Thanks for checking out my issue 🙂

**Comment by achempion** [comment]
The integration should be possible via [custom transformation function](https://hexdocs.pm/waffle/custom_transformation.html). We can add an example to the documentation if someone has it working.

**Comment by achempion** [comment]
feel free to reopen for further help
