### ISSUE TITLE
Consider using AWS instead of ExAWS

### ISSUE THREAD

**Issue by crbelaus** [elixir-waffle/waffle#120]
Currently Waffle is using [ExAWS](https://github.com/ex-aws/ex_aws) which is manually written.

I'm required to calculate a checksum of the S3 objects that the application stores. Unfortunately this is not supported by ExAWS :( At the moment I've forked ExAWS, made the changes and will contribute back a PR so they are hopefully merged into the main library.

Unfortunately, this will keep happening as ExAWS is manually written and needs to be kept up to date with AWS API changes.

--- 

There is [an alternative AWS library](https://github.com/aws-beam/aws-elixir) which is automatically generated from AWS:

> Generated by [aws-codegen](https://github.com/aws-beam/aws-codegen) using the same JSON descriptions of AWS services used to build the [AWS SDK for Go](https://github.com/aws/aws-sdk-go/tree/master/models/apis).

The benefit is that this library is automatically kept up to date with AWS API changes and supports every AWS feature without requiring a person to write it. 

All this started because I could easily do what I need with AWS but it was not supported by ExAWS, which Waffle uses.

---

I am opening this issue as a potential discussion point to consider switching the AWS integration library. This will require some work so I don't want to start working on a pull request unless there is interest on this feature among the maintainers.

**Comment by achempion** [comment]
Hi Cristian,

If we would have a different S3 library, it would be implemented as a separate storage adapter, similar to [waffle_gcs](https://github.com/elixir-waffle/waffle_gcs/). I have plans to extract the current implementation code for S3 into a separate library as well (`waffle_s3`).

It should be possible to use Waffle with ExAWS adapter and compute checksums through the `AWS.Client`. 

Will that work?

**Comment by crbelaus** [comment]
Thanks for the reply @achempion. Writing a separate storage adapter sounds like the best way forward!

For the moment I am writing a patch to `ex_aws` that adds support for checksums in the `put_object` and `head_object` calls and will open a PR soon (I want to test it a bit more).

I think this can be closed. Thanks again.
