### ISSUE TITLE
Adding max_body_length  as optinal hackney parameter

### ISSUE THREAD

**Issue by bitboxer** [elixir-waffle/waffle#121]
### Environment

* Elixir version (elixir -v): 1.16.2
* Waffle version (mix deps): 1.1.8
* Operating system: Mac/Ubuntu

### Expected behavior

It would be nice to have `max_body_length` as an additional parameter for hackney. That way, we could prevent waffle to trying to download super huge image files and process them.

### Actual behavior

Currently, we cannot add that parameter.

**Comment by achempion** [comment]
Thanks for the suggestion, PR is welcome! 
It should be possible to extend the configuration [here](https://github.com/elixir-waffle/waffle/blob/master/lib/waffle/file.ex#L181-L188)

**Comment by bitboxer** [comment]
Yes, I saw. Will do the Pr on this weekend for it 👍 .
