### ISSUE TITLE
Waffle and Hackney Error

### ISSUE THREAD

**Issue by newletorr** [elixir-waffle/waffle#127]
### Environment

* Elixir version (elixir -v): 1.17.3
* Waffle version (mix deps): 1.1.9
* waffle Ecto version:  0.0.12
* Waffle dependencies when applicable (mix deps): Hackney version 1.20.1
* Operating system: Linux
Can't seed my database in production cause this hackney error keeps killing my deployment when i try seed my DB on render.com. This is the error logged: `** (ArgumentError) errors were found at the given arguments:
  * 1st argument: the table identifier does not refer to an existing ETS table
    (stdlib 6.0.1) :ets.lookup_element(:hackney_config, :mod_metrics, 2)
    (hackney 1.20.1) /opt/render/project/src/deps/hackney/src/hackney_metrics.erl:27: :hackney_metrics.get_engine/0
    (hackney 1.20.1) /opt/render/project/src/deps/hackney/src/hackney_connect.erl:75: :hackney_connect.create_connection/5
    (hackney 1.20.1) /opt/render/project/src/deps/hackney/src/hackney_connect.erl:44: :hackney_connect.connect/5
    (hackney 1.20.1) /opt/render/project/src/deps/hackney/src/hackney.erl:335: :hackney.request/5
    (waffle 1.1.9) lib/waffle/file.ex:196: Waffle.File.request/4
    (waffle 1.1.9) lib/waffle/file.ex:157: Waffle.File.save_temp_file/3`
Does anyone know how to get this rectified

**Comment by achempion** [comment]
The issue seems to be related to a configuration and not to a bug in Waffle library.
