### ISSUE TITLE
Feature: Saving stream as a waffle attachment

### ISSUE THREAD

**Issue by fastjames** [elixir-waffle/waffle#130]
Hello, I have a case that seems to be outside the current capabilities of waffle but I wanted to verify that before  I started working on PRs.

In my case, I have a Stream of CSV data that I'd like to store in S3 and treat as a waffle attachment. ex_aws_s3 supports uploading from a Stream, but Waffle.Store.S3 does not handle that case. Am I reading the code correctly? I will probably go ahead and work on this, but I wanted to ask in advance in case I was missing something obvious.

### Environment

* Elixir version (elixir -v): 1.17
* Waffle version (mix deps): 1.1.9
* Waffle dependencies when applicable (mix deps): waffle_ecto 0.0.12
* Operating system: MacOS 14.6.1

**Comment by achempion** [comment]
We only stream uploads from the file path, but it would be nice to accept streams as well
