### ISSUE TITLE
Add ability to generate urls for skipped versions

### ISSUE THREAD

**Issue by alex88** [elixir-waffle/waffle#18]
### Expected behavior

It would be great that url generation works for skipped files, my use case is that after uploading the original version of an image I want to do the thumbnailing on a background queue. Skipping a file would avoid processing the original on upload but I would be able to generate the url later

Current behavior is defined in https://github.com/elixir-waffle/waffle/blob/52602bfae23fb4741dbb4f3aa0d727967b3afe54/lib/waffle/definition/versioning.ex#L9-L18

### Actual behavior

Right now generating a skipped version value returns `nil`

**Comment by achempion** [comment]
Hi, thank you for the feedback!

For now you can either redefine `url` function with `def url(file, version, options) do` or exclude your version from `@versions` attribute and define it as `:noaction` to have url generation in uploader.

I feel like neither of two approaches are correct and we need to better document what `:skip` version is for. In general you should store transformation rules in uploader and we need a way to skip processing on creation stage to do it later and provide guides how to integrate it with background processing solutions (like broadway or similar).
 
If you have any suggestion for DSL it will be helpful.

**Comment by alex88** [comment]
Oh that's nice, my temporary solution was to use

```
def transform(:thumb_256, _), do: {:touch, fn _input, output -> output end}
```

to upload an empty file. Regarding the `:noaction` I might be wrong but it just uploads the full file again which I think is a waste of resources.

Regarding the DSL, I agree it would be great to be able to mark a version as "process later" and use a background queue like broadway to process it, the problem is that at that point you don't have a "master" file anymore but you might have to specify also which other version use as a source for the transformation, so it can be downloaded and processed, right?

**Comment by achempion** [comment]
> Regarding the :noaction I might be wrong but it just uploads the full file again which I think is a waste of resources.

It wouldn't do anything if you exclude this version from `@versions` attribute. Only attributes from that list are addressed on processing stage. `:noaction` here is just to get url generation.

> at that point you don't have a "master" file anymore but you might have to specify also which other version use as a source for the transformation

Great catch, I'll think about it.

**Comment by achempion** [comment]
@alex88 Hi, it will be great to know the final approach you have chosen.

**Comment by alex88** [comment]
@achempion I didn't have a chance to try the other behavior, I'll let you know as soon as I work on that project again, sorry for the delay

**Comment by silvagustin** [comment]
> ```
> def transform(:thumb_256, _), do: {:touch, fn _input, output -> output end}
> ```

I've ended up using this solution too.

Thanks for sharing.

**Comment by mastari** [comment]
How do you call the transform in a changeset before Repo.insert?

**Comment by achempion** [comment]
@mastari hi, can you describe your question in a discussion section? thank you
