### ISSUE TITLE
Delete arc tags from the repo history

### ISSUE THREAD

**Issue by gcauchon** [elixir-waffle/waffle#23]
Since `waffle` is an _hard_ fork from `arc`, I think keeping the old tags/versions might be misleading… It was for me for a few seconds, before I realized from the releases timeline `v0.0.3` > `v0.11.1`.

**Comment by achempion** [comment]
Since `arc` doesn't have tags between `v0.0.0` and `v0.1.0` I thought we can have that range while I do maintainance work (merging all PRs, improving documentation and so on) and then upgrate to `v1.0.0` version line stright away.

Do you think we should completely get rig of all older tags?

**Comment by OvermindDL1** [comment]
Honestly I'd prefer if waffle versions continued where arc left off.

**Comment by gcauchon** [comment]
^this is an even better idea!

Until we reach a certain stability for a viable `1.0` LTA version!

**Comment by achempion** [comment]
@OvermindDL1 I think you're quite right, we should continue the old naming. 

@gcauchon thank you for pointing out! :)
