### ISSUE TITLE
Question: How to delete specific version of an image

### ISSUE THREAD

**Issue by goravbhootra** [elixir-waffle/waffle#24]
Hi,

This is a question rather than a bug. Given the versions:

```@versions [:original, :passport, :thumb]```

How to delete only the `:original` or `:thumb` version after storing the image?

I am storing the original image while user uploads but after specific business logic, only passport size is retained for archival purpose.

The delete function given in documentation deletes all versions of the image. Is passing the specific version enough?

Thanks,
Gorav

**Comment by achempion** [comment]
Right now we have a private `delete_version` function what does what you want. But there are several ways to retain version if you want to:
1) define it as `:skipped` #8 if the scope has an archive flag, delete action wouldn't delete skipped versions
2) use `delete` directly from storage action, it accepts version, wouldn't recommend it through to not depend on implementation details
