### ISSUE TITLE
Add minio support, please!

### ISSUE THREAD

**Issue by wahello** [elixir-waffle/waffle#27]
### Add [minio](https://min.io/) support, please!

**Comment by achempion** [comment]
Hi, thank you for the issue. For now we're officially supporting local storage and S3 integration.

Could you elaborate a little bit more about your issue? Does minio follow some standard API implementation across many providers as s3 does?

Waffle supports many types of storages via adapters which can be implemented by community. Here is the [reference](https://hexdocs.pm/waffle/Waffle.html#module-storage-providers) in documentation.

I'm planning to improve the documentation how to implement a new type of storage but for now if you  have any questions I'm happy to provide any guidance to you.

**Comment by OvermindDL1** [comment]
I thought Minio already supported the S3 API?
