### ISSUE TITLE
Concurrent image uploads sometimes fails (with local backend?)

### ISSUE THREAD

**Issue by luc-tielen** [elixir-waffle/waffle#46]
### Environment

* Elixir version (elixir -v): 1.10.2
* Waffle version (mix deps): 1.1.0
* Waffle dependencies when applicable (mix deps): 
* Operating system: MacOSX (dev machine) / Linux (actual server)

### Expected behavior

When uploading multiple images in quick succession (each image upload requires calling our images endpoint), they should all return the uploaded images on subsequent requests.

### Actual behavior

Some images are correctly uploaded, some failed to upload. I only see this issue on my local environment so maybe related to OSX or `Waffle.Storage.Local` code? It seems to occur more often when I upload a large image and a small image.

I also see the following snippet in the codebase which might explain why some folders/files are missing afterwards?:

```elixir
  defp cleanup!(result, file) do
    # If we were working with binary data or a remote file, a tempfile was
    # created that we need to clean up.
    if file.is_tempfile? do
      File.rm!(file.path)
    end

    result
  end
```

**Comment by achempion** [comment]
> Some images are correctly uploaded, some failed to upload. 

Could you please define "failed to upload" more specifically? Do you get any errors/log messages?

**Comment by luc-tielen** [comment]
I just got back from holidays, there was an error, but I lost it now. If it occurs again, I will post it back here.

**Comment by achempion** [comment]
Feel free to reopen the issue if you'll catch it again.
