### ISSUE TITLE
Feature request: custom validation errors

### ISSUE THREAD

**Issue by samm81** [elixir-waffle/waffle#49]
It would be great if we could attach our own validations when files fail `validate/1`. That way on the file upload forms users would get a better message than "is invalid" (for example: "must be image file").

**Comment by wulymammoth** [comment]
There's already a way to do this: https://github.com/elixir-waffle/waffle/blob/master/lib/waffle/definition/storage.ex#L94-L97. Note that `valid/1` is overrideable, such that you can do as you please

**Comment by muhifauzan** [comment]
@wulymammoth I don't think you can do that. Considering the overidable `validate/1` being handled like this:

```elixir
defp put(definition, {%Waffle.File{} = file, scope}) 
  case definition.validate({file, scope}) 
    true ->
      put_versions(definition, {file, scope})
      |> cleanup!(file)
    _    -> {:error, :invalid_file}
  end
end
```

Returning anything other than `true` will only gives you `{:error, :invalid_file}`
