### ISSUE TITLE
Best practice extracting meta data

### ISSUE THREAD

**Issue by fabrik42** [elixir-waffle/waffle#57]
Hi there!

As I started working with this lib there is one question that I was not able to answer for myself:

What is the best practice to access the files while being uploaded to extract some meta data like exif data or dominant colors?

Right now my approach would be to load the file again in another asynchronous task *after* the upload.

I did not find any hints how this could be done within the worklflows of this lib. Is this excluded on purpose or something worth investigating?

Best,
Christian

### Environment

* Elixir version (elixir -v): Elixir 1.9.4 (compiled with Erlang/OTP 22)
* Waffle version (mix deps): 1.1.0
* Waffle dependencies when applicable (mix deps): n/a
* Operating system: n/a

**Comment by achempion** [comment]
Hi Christian,

When you receive file in your controller you have it on your local
filesystem in a `tmp` directory.

You can extract any metadata on this stage before passing file to
the ecto/waffe.

Does it cover your usecase?

**Comment by fabrik42** [comment]
Hi Boris! 
Thanks for the hint!
Yes, this might be a good approach. I was just wondering if there is a best practice within Waffle, but I am also comfortable to solve it outside of the scope of this lib. 👍
