### ISSUE TITLE
I keep getting `AccessDenied` on file upload to s3

### ISSUE THREAD

**Issue by That-David-Guy** [elixir-waffle/waffle#59]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4
* Waffle version (mix deps):
      {:waffle, "\~> 1.1.1"},
* Waffle dependencies when applicable (mix deps):
      {:ex_aws, "\~> 2.1.2"},
      {:ex_aws_s3, "\~> 2.0"},
      {:hackney, "\~> 1.9"},
      {:sweet_xml, "\~> 0.6"},
      {:waffle_ecto, "\~> 0.0.9"}
* Operating system: macOS Catalina 10.15.6

### Expected behavior

Following example from https://elixircasts.io/file-uploads-with-waffle, and s3 setup from https://www.poeticoding.com/aws-s3-in-elixir-with-exaws.

I'm expecting to be able to upload a single png file to an s3 bucket from my website running on my local computer in dev mode. I can not do this.

### Actual behavior

I get this error (seems to happen on the `|> cast_attachments(attrs, [:test_image])` step)

```
[error] {:error, [{:http_error, 403, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>998297CFD9477E36</RequestId><HostId>wT2XcVteOn0YSJgBQ+SUn/eQkkMNmJawekxPaX9FG8Cwfr6pN2mOsQgmqm1QclgXYEpXG23IyQ4=</HostId></Error>", headers: [{"x-amz-request-id", "998297CFD9477E36"}, {"x-amz-id-2", "wT2XcVteOn0YSJgBQ+SUn/eQkkMNmJawekxPaX9FG8Cwfr6pN2mOsQgmqm1QclgXYEpXG23IyQ4="}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Tue, 04 Aug 2020 11:04:11 GMT"}, {"Server", "AmazonS3"}], status_code: 403}}, {:http_error, 403, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>4P5KDK1WDTDW1T5M</RequestId><HostId>n5rvGfKaJ8XeiA0v/ZnqZC/ssqYLO68V5KK6XT7K6UNDQpIBIjRlvnLSYlunKSAstRjlMgf37jA=</HostId></Error>", headers: [{"x-amz-request-id", "4P5KDK1WDTDW1T5M"}, {"x-amz-id-2", "n5rvGfKaJ8XeiA0v/ZnqZC/ssqYLO68V5KK6XT7K6UNDQpIBIjRlvnLSYlunKSAstRjlMgf37jA="}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Tue, 04 Aug 2020 11:04:11 GMT"}, {"Server", "AmazonS3"}], status_code: 403}}]}
```

### What I've tried so far

If I run `iex -S mix` and use `ExAws` directly it does work. The following uploading a file to my s3 bucket:

```
iex(2)> local_image = File.read!("assets/static/images/phoenix.png")
<<137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 2, 216, 0,
  0, 0, 99, 8, 6, 0, 0, 0, 161, 65, 119, 154, 0, 0, 0, 25, 116, 69, 88, 116, 83,
  111, 102, 116, 119, 97, 114, 101, 0, ...>>
iex(3)> ExAws.S3.put_object("maw-static-dev", "images/elixir_logo.png", local_image)
%ExAws.Operation.S3{
  body: <<137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 2,
    216, 0, 0, 0, 99, 8, 6, 0, 0, 0, 161, 65, 119, 154, 0, 0, 0, 25, 116, 69,
    88, 116, 83, 111, 102, 116, 119, 97, 114, 101, ...>>,
  bucket: "maw-static-dev",
  headers: %{},
  http_method: :put,
  params: %{},
  parser: &ExAws.Utils.identity/1,
  path: "images/elixir_logo.png",
  resource: "",
  service: :s3,
  stream_builder: nil
}
```

My config file looks like this.

```
config :waffle,
  storage: Waffle.Storage.S3, # or Waffle.Storage.Local
  bucket: "maw-static-dev",
  asset_host: "http://static.dev.makeawesomeworkshop.com", # or {:system, "ASSET_HOST"}, # This is not up yet
  virtual_host: true

config :ex_aws,
  access_key_id: "my_key",
  secret_access_key: "my_secret_key",
  region: "ap-southeast-2",
  json_codec: Jason,
  s3: [
    scheme: "https://",
    host: "s3.ap-southeast-2.amazonaws.com",
    region: "ap-southeast-2"
  ]
```

I'm assuming its something to do with my config, but I'm having a lot of trouble debugging this. Any ideas what I'm doing wrong? Is there a GitHub repo that has an example phoenix project that does a single upload to a s3 bucket that I can compare against?

**Comment by achempion** [comment]
Hi, David

You could check this PR for additional examples:
https://github.com/elixir-waffle/waffle/pull/55.

Also, you could inspect configuration for AWS S3 tests.
https://github.com/elixir-waffle/waffle/blob/master/test/storage/s3_test.exs#L121

`virtual_host` will be ignored if you have `asset_host` option defined.

**Comment by That-David-Guy** [comment]
Thanks @achempion . It'll take a few days for me to look at this again, but I'll make sure to update this issue

**Comment by That-David-Guy** [comment]
Found the issue, I needed to turn off all the settings at

`aws website / s3 / bucket /permissions / Block public access (bucket settings)`

And now it works 😀 In the long run I’ll need to do more work here as I’ll want the images to only be public for a short period of time. But for now it’s good enough.

Thanks again for your help!
