### ISSUE TITLE
how to use image magik security policy

### ISSUE THREAD

**Issue by steffenix** [elixir-waffle/waffle#64]
In order to make sure image magik vulnerabilities aren't making my system vulnerable I would like to use security policy, is their a way to configure it?
Ref: https://imagemagick.org/script/security-policy.php

**Comment by achempion** [comment]
Hi Steffel,

ImageMagick configuration is out of scope of this library, but I'm
welcome to patches about general practices of file uploading.

My take is to use proper `content-type` detection by magic bytes. You
can do this with elixir or using `file` unitily.

Here is an example of content-type detection

```elixir
+  def content_type(filepath) do
+    case System.cmd("file", ["--mime", "--brief", filepath]) do
+      {file_data, 0} ->
+        content_type =
+          file_data
+          |> extract_content_type
+          |> transform_content_type
+
+        {:ok, content_type}
+
+      {error, 1} ->
+        {:error, error}
+    end
+  end
+
+  defp transform_content_type(content_type) do
+    case content_type do
+      "inode/x-empty" ->
+        "application/octet-stream"
+
+      _ ->
+        content_type
+    end
+  end
```

**Comment by achempion** [comment]
Forgot to include `extract_content_type` function

```elixir
+  defp extract_content_type(file_data) do
+    Regex.named_captures(~r/^(?<content_type>.+);/, file_data)["content_type"]
+  end
```

**Comment by achempion** [comment]
About the policy file,

It looks like you can place it to any default directory and it'll be
detected automatically or set the `MAGICK_CONFIGURE_PATH` environment
variable with custom location.

**Comment by achempion** [comment]
Will be implemented in https://github.com/elixir-waffle/waffle/issues/14
