### ISSUE TITLE
Plans to support Multi Tenancy?

### ISSUE THREAD

**Issue by sikula** [elixir-waffle/waffle#72]
Is there plans to support multi tenancy for uploads?  We would like to isolate customer's data by some sort of prefix. - e.g. /customer_id/file_name.  What's the current recommended way of doing this?

**Comment by achempion** [comment]
You can use either [`storage_dir`](https://hexdocs.pm/waffle/Waffle.Definition.Storage.html#module-by-overriding-the-relevent-functions-in-definition-modules) configuration or [`storage_dir_prefix`](https://hexdocs.pm/waffle/Waffle.Storage.Local.html) if you use Local storage and want to to have a different storage directory from url.
