### ISSUE TITLE
ExOptimizer Integration?

### ISSUE THREAD

**Issue by niccolox** [elixir-waffle/waffle#76]
Is Waffle compatible with ExOptimizer?

https://framagit.org/tcit/ex_optimizer/-/issues/2

Is it possible to pass a Waffle file into another function?

``
|> ExOptimizer.optimize(path_to_image)
|> cast_attachments(changeset, params, [:image_file], allow_urls: true)
```

**Comment by achempion** [comment]
Right now we have [`Waffle.Processor`](https://hexdocs.pm/waffle/1.1.4/Waffle.Processor.html) module which in general expects executable with its arguments.

You can optimise the file before passing to Waffle, but I think is bad approach because you want to run file validations first.

We can extend Processor module to have custom elixir function for optimisation instead of executable.

**Comment by achempion** [comment]
Like a temporary workaround you can create an elixir file which will call the `ExOptimizer` library and then configure your transformation to call this mule, like 

```elixir
def transform(:thumb, _) do
    {:elixir, "run optimise.exs"}
  end
```

Or create a different shell executable which will call the elixir file with optimisation logic.

**Comment by niccolox** [comment]
Thanks @achempion for the things to try today and the future directions

> We can extend Processor module to have custom elixir function for optimisation instead of executable.

how can this be done? whats your thinking here? 
is this doable today is this a feature request?

I'd love to be able to do advanced workflows in Elixir modules and not just scripts (although that is a great suggestion)

Any obvious feature idea is to parse an image through a ML pattern recognition to check for offensive or unacceptable content, you get the idea. Kind of equivalent to Burnex for burner email filtering when accepting email on signup

**Comment by achempion** [comment]
> An obvious feature idea is to parse an image through a ML pattern recognition to check for offensive or unacceptable content, you get the idea

It can be done already with custom validation flow.

**Comment by thomasfortes** [comment]
> how can this be done? whats your thinking here?
> is this doable today is this a feature request?

Not sure if you still need this, but it is reasonably easy, not sure if @achempion wants a pull request or is not interested in this feature, but you just need to add a single line to the processor.ex

```elixir
  defp apply_transformation(_, :skip), do: {:ok, nil}
  defp apply_transformation(file, :noaction), do: {:ok, file}
  defp apply_transformation(file, {:custom_func, func}), do: func.(file)
```

And then you can use it in your definition like this:

```elixir
  def transform(:thumb, _) do
    #{:convert, "-strip -thumbnail 250x250^ -gravity center -extent 250x250 -format png", :png}
    {:custom_func, &generate_thumb(&1, 250)}
  end

  defp generate_thumb(file, width) do
    {:ok, thumb} = Vix.Vips.Operation.thumbnail(file.path, width)
    new_path = Waffle.File.generate_temporary_path(file)
    case Vix.Vips.Image.write_to_file(thumb, new_path) do
      :ok ->
        new_file = %Waffle.File{file | path: new_path, is_tempfile?: true}
        {:ok, new_file}
      _ -> {:error, "It wasn't possible to generate a thumbnail"}
    end
  end
```

**Comment by niccolox** [comment]
very nice, just circling back to this issue after experimenting with Image and Vix https://hexdocs.pm/image

I got drawn into Image because of its Bumblebee integrations and so full circle

thanks guys
