### ISSUE TITLE
How to rename stored file?

### ISSUE THREAD

**Issue by AndrewKlymchuk** [elixir-waffle/waffle#79]
Hello. I use waffle with [waffle_gcs](https://github.com/kolorahl/waffle_gcs). I had changed the way how file name is constructed and now need to change the name of all already stored files so they remain accessible. What is the best way to do it?

**Comment by achempion** [comment]
You need to write migration task to rename files on Google Cloud and update filename field accordingly in a database.

**Comment by AndrewKlymchuk** [comment]
@achempion, thank you for response!
