### ISSUE TITLE
S3 Support for filebase.com 

### ISSUE THREAD

**Issue by mazz** [elixir-waffle/waffle#83]
Does waffle support alternate S3 endpoints? i.e. `https://s3.filebase.com`

**Comment by achempion** [comment]
Hey, you can use any storage that is compatible with S3, i.e. firebase, minio and so on

here is the [docs](https://hexdocs.pm/waffle/Waffle.Storage.S3.html#module-alternate-s3-configuration-example)

Feel free to send a PR if you think something is missing

**Comment by achempion** [comment]
Also, similar question https://github.com/elixir-waffle/waffle/issues/62
