### ISSUE TITLE
Waffle.Storage.Local can delete data of different user/scope

### ISSUE THREAD

**Issue by Calamari** [elixir-waffle/waffle#88]
Using the local storage option, I have the problem that the following (simplified) code works:

```elixir
    file = %Plug.Upload{
      path: "test/myapp/fixtures/sample.pdf",
      filename: "sample.pdf"
    }

    {:ok, file_id} = UserFile.store_file(file, "boom", %{id: "one"})

    :ok = UserFile.delete({file_id, %{id: "two"}})
    :ok = UserFile.delete({"foo", %{id: "one"}})
```

I can create a file with one scope (user), and can delete it with another one.
I have not tried it with S3 yet, and I suspect (and hope) it would not be possible there, since I think Amazon is doing a scope-check, but it is totally weird that you can do that with the Local storage option.

I would not use this in production, but I use this storage option for testing, and since it (hopefully) works differently than S3 storage, it makes some cases impossible to test.

### Environment

* Elixir version (elixir -v): 1.12.1
* Waffle version (mix deps): 1.1.5
* Operating system: Linux Mint 19.3 Tricia

### Expected behavior
It should return an error, or at least not remove the file.

### Actual behavior
It returns `:ok` and deletes the file that was created with a different scope.

**Comment by achempion** [comment]
Hey, the "scope" name can be very confusing but it doesn't add any scope by itself but can be used for custom path generation.

In your case, you need to use different storage directory depending on a scope, here is [related section in documentation](https://hexdocs.pm/waffle/Waffle.Definition.Storage.html#module-by-overriding-the-relevent-functions-in-definition-modules).
