### ISSUE TITLE
sweet_xml vulnerability on 0.6

### ISSUE THREAD

**Issue by mcbloch** [elixir-waffle/waffle#95]
sweet_xml has a XML bomb vulnerability in version 0.6 which is used by this library. They fixed it in 0.7.

https://github.com/kbrw/sweet_xml/issues/71

### Environment

* Waffle version (mix deps): 1.1.6
* Waffle dependencies when applicable (mix deps): sweet_xml 0.6.6

**Comment by achempion** [comment]
Hey, thank you for the report. I've updated deps two weeks ago and we're currently [on recent version](https://github.com/elixir-waffle/waffle/blob/master/mix.lock#L25) `0.7.2`.

This dependency is also optional and only needed for S3 integration.
